{{- include "vllm-kserve.validateAll" . }}
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    {{- include "vllm-kserve.inferenceServiceAnnotations" . | nindent 4 }}
  name: {{ include "vllm-kserve.inferenceServiceName" . }}
  labels:
    {{- if eq .Values.servingTopology "singleNode" }}
    opendatahub.io/dashboard: "true"
    {{- end }}
    networking.kserve.io/visibility: exposed
spec:
  predictor:
    minReplicas: {{ .Values.scaling.minReplicas }}
    {{- if eq .Values.servingTopology "singleNode" }}
    {{- if gt (int .Values.scaling.maxReplicas) 0}}
    maxReplicas: {{ .Values.scaling.maxReplicas }}
    {{- end }}
    {{- if .Values.scaling.scaleMetric }}
    scaleMetric: {{ .Values.scaling.scaleMetric }}
    {{- end }}
    {{- if .Values.scaling.scaleTarget }}
    scaleTarget: {{ .Values.scaling.scaleTarget }}
    {{- end }}
    {{- end }}
    deploymentStrategy:
      {{- toYaml .Values.scaling.rawDeployment.deploymentStrategy | nindent 6 }}
    model:
      args:
        {{- if .Values.model.modelNameOverride }}
        - --served-model-name={{ .Values.model.modelNameOverride }}
        {{- else }}
        - --served-model-name={{ "{{" }} .Name {{ "}}" }} {{/* Escaping brackets for downward API template */}}
        {{- end }}
      {{- if .Values.model.args }}
        {{- toYaml .Values.model.args | nindent 8 }}
      {{- end }}
      {{- if .Values.model.env }}
      env:
        {{- toYaml .Values.model.env | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      modelFormat:
        name: vLLM
      name: ''
      {{- with .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 8 }}
        {{- end }}
      {{- if .Values.servingRuntime.useExisting }}
      runtime: {{ .Values.servingRuntime.useExisting }}
      {{- else }}
      runtime: {{ include "vllm-kserve.servingRuntimeName" . }}
      {{- end }}
      {{- with .Values.model }}
      {{- if eq (lower .mode) "uri" }}
      storageUri: {{ .uri }}
      {{- else if eq (lower .mode) "pvc"}}
      storageUri: pvc://{{ .pvc.name }}/data/models/{{ .pvc.downloadModel.huggingfaceModelRepo }}
      {{- else if eq (lower .mode) "s3"}}
      storage:
        key: {{ .s3.key }}
        path: {{ .s3.path }}
      {{- end }}
      {{- end }}
    {{- if .Values.tolerations }}
    tolerations:
      {{- toYaml .Values.tolerations | nindent 8 }}
    {{- end }}
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if eq .Values.servingTopology "multiNode" }}
    workerSpec:
      pipelineParallelSize: {{ .Values.multiNode.pipelineParallelSize }}
      tensorParallelSize: {{ .Values.multiNode.tensorParallelSize }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: worker-container
          {{- with .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
    {{- end }}
