{{- if .Values.endpoint.auth.enabled }}
{{- range $serviceAccount := .Values.endpoint.auth.serviceAccounts }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vllm-kserve.fullname" $ }}-{{ $serviceAccount.name }}-view
  labels:
    {{- include "vllm-kserve.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccount.name }}
    namespace: {{ $serviceAccount.namespace | default $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vllm-kserve.fullname" $ }}-view
{{- end }}
{{- end }}
