apiVersion: v1
kind: Service
metadata:
  name: {{ include "phoenix.fullname" . }}
  {{- if .Values.openshiftOauth.enabled }}
  annotations:
     service.alpha.openshift.io/serving-cert-secret-name: {{ include "phoenix.fullname" . }}-tls
  {{- end }}
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: phoenix
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if .Values.openshiftOauth.enabled }}
    - name: oauth-proxy
      port: 8443
      targetPort: oauth-proxy
      protocol: TCP
    {{- end }}
  selector:
    {{- include "phoenix.selectorLabels" . | nindent 4 }}
