apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "phoenix.fullname" . }}
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "phoenix.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "phoenix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "phoenix.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "phoenix.serviceAccountName" . }}
      containers:
        - name: phoenix
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
              - python
          args:
              - -m
              - phoenix.server.main
              - serve
          {{- if hasKey .Values.openai.key "existingSecret" }}
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                {{- with .Values.openai.key.existingSecret }}
                {{- toYaml . | nindent 18 }}
                {{- end }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "phoenix.fullname" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          ports:
              - name: http
                containerPort: {{ .Values.service.port }}
                protocol: TCP
              - name: metrics
                containerPort: 9090
                protocol: TCP
              - name: grcp
                containerPort: 4317
                protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
              - mountPath: /var/lib/phoenix
                name: phoenix
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "phoenix.fullname" . }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.volumeClaimTemplates.requests.storage }}
