{{- if include "gitops-tenant.gitops-name" . }}
{{- range $role := .Values.additionalRoles }}
{{- range $namespace := $.Values.namespaces }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $role.name }}
  namespace: {{ include "gitops-tenant.namespace" ( dict "namespace" $namespace "context" $ ) }}
  labels:
    {{- include "gitops-tenant.labels" $ | nindent 4 }}
rules:
  {{- toYaml $role.rules | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
