{{- range $namespace := .Values.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gitops-tenant.namespace" ( dict "namespace" $namespace "context" $ ) }}-users
  namespace: {{ include "gitops-tenant.namespace" ( dict "namespace" $namespace "context" $ ) }}
  labels:
    {{- include "gitops-tenant.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $namespace.adminGroupRole }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ include "gitops-tenant.admin-group" $ }}
{{- end }}
