{{- if .Values.adminGroup.create -}}
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: {{ include "gitops-tenant.admin-group" . }}
  labels:
    {{- include "gitops-tenant.labels" . | nindent 4 }}
users:
  {{- toYaml .Values.adminGroup.members | nindent 2 }}
{{- end }}
