{{- if .Values.grafana.instance.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-proxy
data:
  session_secret: '{{ default (randAlphaNum 20) .Values.sessionSecret | b64enc }}'
type: Opaque
{{- end }}
