{{- if .Values.notebookController.enabled }}
{{- if .Values.notebookController.culling.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: notebook-controller-culler-config
  labels:
    {{- include "odh.labels" . | nindent 4 }}
data:
  CULL_IDLE_TIME: "{{ .Values.notebookController.culling.cullIdleTime }}"
  ENABLE_CULLING: "{{ .Values.notebookController.culling.enabled }}"
  IDLENESS_CHECK_PERIOD: "{{ .Values.notebookController.culling.idlenessCheckPeriod }}"
{{- end }}
{{- end }}
