{{- range $role := .Values.additionalRoles }}
{{- range $namespace := $.Values.namespaces }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $role.name }}
  namespace: {{ include "ml-gitops-tenant.namespace" ( dict "namespace" $namespace "context" $ ) }}
rules:
  {{- toYaml $role.rules | nindent 2 }}
{{- end }}
{{- end }}