apiVersion: v1
kind: Service
metadata:
  name: {{ include "llamastack-playground.fullname" . }}
  labels:
    {{- include "llamastack-playground.labels" . | nindent 4 }}
  {{- if .Values.openshiftOauth.enabled }}
  annotations:
     service.alpha.openshift.io/serving-cert-secret-name: {{ include "llamastack-playground.fullname" . }}-tls
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.openshiftOauth.enabled }}
    - port: 8443
      targetPort: oauth-proxy
      protocol: TCP
      name: oauth
    {{- end }}
  selector:
    {{- include "llamastack-playground.selectorLabels" . | nindent 4 }}
