odhCommon:
  # -- Enable install of ODH Common resources
  enabled: true

odhDashboard: 
  # -- Enable install of the ODH Dashboard instance
  enabled: true
  overlays: []

notebookController:
  enabled: true
  culling:
    enabled: true
    cullIdleTime: '240'
    idlenessCheckPeriod: "5"

notebookImages:
  # -- Enable the install of additional Jupyter Notebook images
  enabled: true

modelMesh:
  # -- Enable install of the Model Mesh instance
  enabled: true
  overlays:
    - odh-model-controller

dataSciencePipelines:
  # -- Enable install of the Data Science Pipelines (KubeFlow Pipelines) component
  enabled: true
  overlays:
    - metadata-store-mariadb
    - ds-pipeline-ui
    - object-store-minio
    - integration-odhdashboard
    - default-configs

grafana: 
  operator:
    # -- Enable install of the Grafana Operator
    enabled: false
  instance:
    # -- Enable install of a Grafana instance
    enabled: false

prometheus:
  operator:
    # -- Enable install of the Prometheus Operator
    enabled: false
    # -- Enable install of a Prometheus instance
  instance:
    enabled: false

repos:
  # -- ODH Manifests URL base
  manifestsUrl: 'https://github.com/opendatahub-io/odh-manifests/tarball/'
  # Overrides the manifestsVersion whose default is the chart appVersion.
  # -- Used to overwrite teh manifestsURL version from the chart appVersion
  # @default -- Chart appVersion
  manifestsVersion: ""
