odhCommon:
  # -- Enable install of ODH Common resources
  enabled: true

odhDashboard: 
  # -- Enable install of the ODH Dashboard instance
  enabled: true
  overlays:
    - authentication

notebookController:
  enabled: true

additionalNotebooks:
  # -- Enable the install of additional Jupyter Notebook images via overlays
  enabled: true
  # -- Notebook overlays to include in the deployment
  overlays:
    - additional
    # - cuda-11.0.3

modelMesh:
  # -- Enable install of the Model Mesh instance
  enabled: true
  overlays:
    - odh-model-controller

dataSciencePipelines:
  # -- Enable install of the Data Science Pipelines (KubeFlow Pipelines) component
  enabled: true
  overlays:
    - metadata-store-mariadb
    - ds-pipeline-ui
    - object-store-minio
    - default-configs

grafana: 
  operator:
    # -- Enable install of the Grafana Operator
    enabled: false
  instance:
    # -- Enable install of a Grafana instance
    enabled: false

prometheus:
  operator:
    # -- Enable install of the Prometheus Operator
    enabled: false
    # -- Enable install of a Prometheus instance
  instance:
    enabled: false

jupyterHub: 
  # -- Enable the install of a JupyterHub instance (Depreciated)
  enabled: false
  singleUserProfile: 
    # -- Enable the configuration of a singleUserProfile for JupyterHub
    enabled: false
    # profile:
    #   profiles:
    #   - name: preload repos
    #     env:
    #       - name: JUPYTER_PRELOAD_REPOS
    #         value: https://github.com/guimou/xraylab_notebooks.git
    #   - name: globals
    #     resources:
    #       requests:
    #         memory: 500m
    #         cpu: 500m
    #       limits:
    #         memory: 1Gi
    #         cpu: 1

repos:
  # -- ODH Manifests URL base
  manifestsUrl: 'https://github.com/opendatahub-io/odh-manifests/tarball/'
  # Overrides the manifestsVersion whose default is the chart appVersion.
  # -- Used to overwrite teh manifestsURL version from the chart appVersion
  # @default -- Chart appVersion
  manifestsVersion: ""
