{
 "title": "Nvidia GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "tags": [
  "gpu",
  "kubernetes-mixin"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(DCGM_FI_PROF_GR_ENGINE_ACTIVE, instance)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(DCGM_FI_PROF_GR_ENGINE_ACTIVE, gpu)"
    }
   },
   {
    "name": "mig",
    "query": {
     "query": "label_values(DCGM_FI_PROF_GR_ENGINE_ACTIVE, GPU_I_PROFILE)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(DCGM_FI_PROF_GR_ENGINE_ACTIVE{instance=~\"$instance\"}) by (instance, gpu)) / count(count(DCGM_FI_PROF_GR_ENGINE_ACTIVE{instance=~\"$instance\"}) by (instance, device))"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{instance=~\"$instance\", gpu=~\"$gpu\"})/sum(DCGM_FI_DEV_FB_USED{instance=~\"$instance\", gpu=~\"$gpu\"}+DCGM_FI_DEV_FB_FREE{instance=~\"$instance\", gpu=~\"$gpu\"})"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_PROF_GR_ENGINE_ACTIVE{GPU_I_PROFILE=\"\",instance=~\"$instance\", gpu=~\"$gpu\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-full{{gpu}}"
    },
    {
     "expr": "AVG(DCGM_FI_PROF_GR_ENGINE_ACTIVE{GPU_I_PROFILE!=\"\",instance=~\"$instance\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-mig{{gpu}}"
    }
   ]
  },
  {
   "title": "Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": " AVG(DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{instance=~\"$instance\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}-tensor"
    },
    {
     "expr": " AVG(DCGM_FI_PROF_PIPE_FP64_ACTIVE{instance=~\"$instance\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}-fp64"
    },
    {
     "expr": " AVG(DCGM_FI_PROF_PIPE_FP32_ACTIVE{instance=~\"$instance\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}-fp32"
    },
    {
     "expr": " AVG(DCGM_FI_PROF_PIPE_FP16_ACTIVE{instance=~\"$instance\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}-fp16"
    }
   ]
  },
  {
   "title": "# GPUs / MIGs",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(label_replace(DCGM_FI_PROF_GR_ENGINE_ACTIVE{instance=~\"$instance\",GPU_I_PROFILE!=\"\"}, \"GPU\",\"$1\",\"GPU_I_PROFILE\",\"(.*)\")) by (instance,GPU)",
     "legendFormat": "{{ GPU }}"
    },
    {
     "expr": "count(label_replace(DCGM_FI_PROF_GR_ENGINE_ACTIVE{instance=~\"$instance\",GPU_I_PROFILE!=\"\"} >= 0.5, \"GPU\",\"$1\",\"GPU_I_PROFILE\",\"(.*)\")) by (instance,GPU)",
     "legendFormat": "{{ GPU }}"
    },
    {
     "expr": "count(label_replace(DCGM_FI_PROF_GR_ENGINE_ACTIVE{instance=~\"$instance\",GPU_I_PROFILE=\"\"}, \"GPU\",\"$1\",\"modelName\",\"(.*)\")) by (GPU)",
     "legendFormat": "{{ GPU }}"
    },
    {
     "expr": "count(label_replace(DCGM_FI_PROF_GR_ENGINE_ACTIVE{instance=~\"$instance\",GPU_I_PROFILE=\"\"} >= 0.5, \"GPU\",\"$1\",\"modelName\",\"(.*)\")) by (GPU)",
     "legendFormat": "{{ GPU }}"
    }
   ]
  },
  { "title": "Memory Utilization", "type": "timeseries", "gridPos": { "h": 9, "w": 9, "x": 6, "y": 9 }, "fieldConfig": { "defaults": { "unit": "percent" } } },
  {
   "title": "GPU SM Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_PROF_SM_ACTIVE{instance=~\"$instance\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}-active"
    },
    {
     "expr": "avg(DCGM_FI_PROF_SM_OCCUPANCY{instance=~\"$instance\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}-occupancy"
    }
   ]
  },
  {
   "title": "# Timeslicing",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$instance\",resource=~\"nvidia_com_.+_shared\"}) by (node,resource)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$instance\",resource=~\"nvidia_com_.+_shared\"}) by (node,resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "AVG(DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance\", gpu=~\"$gpu\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "AVG(DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance\", gpu=~\"$gpu\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "PCIe Tx/Rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-DCGM_FI_PROF_PCIE_TX_BYTES{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "{{instance}}-gpu{{gpu}}-Tx"
    },
    {
     "expr": "DCGM_FI_PROF_PCIE_RX_BYTES{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "{{instance}}-gpu{{gpu}}-Rx"
    }
   ]
  },
  {
   "title": "Cycles Memory Interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "AVG(DCGM_FI_PROF_DRAM_ACTIVE{instance=~\"$instance\", gpu=~\"$gpu\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}"
    }
   ]
  }
 ]
}