apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
data:
{{- ( include "gen.secret" . ) | indent 2 -}}
