{{- if .Values.auth.enabled }}
{{- include "llm-d-kserve.validateLegacyTokenInAnotherNamespace" . }}
{{- $items := index (fromJson (include "llm-d-kserve.normalizedServiceAccounts" $)) "items" -}}
{{- range $items -}}
{{- if not (index . "createLegacyToken") }}
{{- if (index . "create") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ index . "name" }}
  namespace: {{ index . "namespace" }}
  labels:
    {{- include "llm-d-kserve.labels" $ | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "llm-d-kserve.fullname" $ }}-{{ index . "name" }}-view
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "llm-d-kserve.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ index . "name" }}
    namespace: {{ index . "namespace" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "llm-d-kserve.fullname" $ }}-view
{{- end }}
{{- end -}}
{{- end }}
